#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
GOAA First Onboarding Executor
===============================
Reads first-activation-guide.yaml → body initialization (single-track: workspace IS the body · creates _Memory/ four layers + expands identity/ three files) → guides step by step (CLI interaction) → generates identity/owner-profile.md (machine read-only)

Usage:
    python3 first-activation-guide.py                    # default onboarding flow
    python3 first-activation-guide.py --dry-run          # show the flow without interacting

Design:
    - Single-track body (2026-08-27 ruling): the workspace IS the body — onboarding bootstraps memory/identity layers so mechanism references close the loop
    - Staged onboarding (Plan C): first activation collects only the required items; continuous supplementation happens in daily conversations
    - The output is machine-immutable (modification rights belong solely to the human)
"""

import argparse
import datetime
import os
import sys

try:
    import yaml
except ImportError:
    print("[FAIL] PyYAML is required. Install it first: pip install pyyaml")
    sys.exit(1)

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(SCRIPT_DIR, "first-activation-guide.yaml")
DEFAULT_TARGET = os.path.join(SCRIPT_DIR, "..", "..", "identity", "owner-profile.md")


def load_config(path: str) -> dict:
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def ask(prompt: str, required: bool = True, hint: str = "") -> str:
    """Ask the owner a question and collect the answer."""
    full = prompt
    if hint:
        full += f"\n  (hint: {hint})"
    while True:
        try:
            answer = input(full + "\n> ").strip()
        except (EOFError, KeyboardInterrupt):
            print("\n[interrupted] Onboarding aborted; nothing collected is written to disk.")
            sys.exit(0)
        if answer or not required:
            return answer
        print("  ⚠️ This item is required — please answer:")


def build_profile(data: dict, frozen_note: str) -> str:
    """Generate the owner profile Markdown (human semantics · machine read-only)."""
    now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    fields = data.get("master_series", {})
    lines = [
        "# Owner Profile (machine-immutable · only the owner may edit)",
        "",
        f"> Generated by first onboarding ({now}) · machine read-only · modification rights belong solely to the human",
        f"> {frozen_note}",
        "",
        "## Basic Info",
        "| Item | Value |",
        "|----|----|",
        f"| Instance name | {data.get('agent_name', '')} |",
        f"| Owner name | {fields.get('master_name', '')} |",
        "",
        "## Background",
        fields.get("background", ""),
        "",
        "## Goals",
        fields.get("goals", ""),
        "",
        "## Collaboration Preferences",
        f"- Communication style: {fields.get('comm_style', '')}",
        f"- Working rhythm: {fields.get('rhythm', 'not stated')}",
        "",
        "## Boundaries & Authorization",
        f"- 🔴 Red lines (never do): {fields.get('boundaries', '')}",
        f"- ✅ Authorization (may act autonomously): {fields.get('authorizations', 'not stated')}",
        "",
        "## Supplement",
        fields.get("extra", ""),
        "",
        "---",
        "*This profile is continuously supplemented: new preferences/habits the machine learns in daily conversations are appended here after the owner confirms.*",
        "",
    ]
    return "\n".join(lines)


def ensure_body(script_dir: str, dry_run: bool = False) -> dict:
    """Single-track body initialization (2026-08-27 single-track ruling):
    The workspace IS the body — bootstrap the memory layer and identity layer so that
    mechanism references (_Memory/, identity/) form a closed loop.
    dry_run=True computes paths only, does not write.
    Returns {body_root, memory_root, identity_root}.
    """
    body_root = os.path.normpath(os.path.join(script_dir, "..", ".."))  # en/
    memory_root = os.path.join(body_root, "_Memory")
    identity_root = os.path.join(body_root, "identity")

    if dry_run:
        return {"body_root": body_root, "memory_root": memory_root, "identity_root": identity_root}

    # ① Memory layer (four subdirs referenced by mechanisms: _Memory/distill·history·index·snapshot)
    for sub in ("distill", "history", "index", "snapshot"):
        os.makedirs(os.path.join(memory_root, sub), exist_ok=True)

    # ② Identity templates expansion (templates/identity/ → identity/)·no overwrite if exists (owner-editable)
    tpl_dir = os.path.join(body_root, "templates", "identity")
    if os.path.isdir(tpl_dir):
        for fname in ("SOUL.md", "IDENTITY.md", "USER.md"):
            src = os.path.join(tpl_dir, fname)
            dst = os.path.join(identity_root, fname)
            if os.path.isfile(src) and not os.path.exists(dst):
                try:
                    with open(src, "r", encoding="utf-8") as f:
                        content = f.read()
                    os.makedirs(identity_root, exist_ok=True)
                    with open(dst, "w", encoding="utf-8") as f:
                        f.write(content)
                    print(f"   🧩 Identity template expanded: {fname} → identity/{fname}")
                except OSError as e:
                    print(f"   ⚠️ Identity template expansion failed {fname}: {e}")

    return {"body_root": body_root, "memory_root": memory_root, "identity_root": identity_root}


def run(config: dict, dry_run: bool = False) -> str:
    act = config["activation"]
    data = {"agent_name": "", "master_series": {}}

    # ⓪ Body initialization (single-track · workspace IS the body)
    body = ensure_body(SCRIPT_DIR, dry_run=dry_run)
    if dry_run:
        print(f"\n[dry-run] body init: {body['body_root']} (_Memory/ four layers + identity/ three files · no write)")

    # ① Welcome + self-introduction
    intro = act.get("intro", {})
    print("=" * 60)
    print(intro.get("title", "Welcome"))
    print("=" * 60)
    print(intro.get("content", ""))
    print("=" * 60)

    # ② Naming
    naming = act.get("naming", {})
    print(f"\n[Step 2 · Naming]")
    if dry_run:
        data["agent_name"] = "(example name)"
    else:
        data["agent_name"] = ask(naming.get("prompt", "What would you like to call me?"),
                                 naming.get("required", True),
                                 naming.get("hint", ""))

    # ③ Owner info collection
    series = act.get("master_series", {})
    print(f"\n[Step 3 · Getting to know the owner] {len(series.get('fields', []))} item(s) (* = required)")
    for field in series.get("fields", []):
        fname = field["field"]
        required = field.get("required", True)
        mark = "*" if required else " "
        prompt = f"[{mark}] {field['prompt']}"
        if dry_run:
            data["master_series"][fname] = "(example answer)"
        else:
            data["master_series"][fname] = ask(prompt, required)

    # ④ Review confirmation
    review = act.get("review", {})
    print(f"\n[Step 4 · Review confirmation]")
    print(review.get("prompt", ""))
    print(build_profile(data, act.get("finalize", {}).get("frozen_note", "")))
    if not dry_run:
        while True:
            ok = input("All correct? (y/revision note) > ").strip().lower()
            if ok in ("y", "yes", "ok"):
                break
            print("  ⚠️ Demo version: edit the generated profile file directly for changes; the production version will support per-item correction.")

    # ⑤ Save to disk
    finalize = act.get("finalize", {})
    target = finalize.get("target", "identity/owner-profile.md")
    if dry_run:
        print(f"\n[dry-run] would write to: {target}")
        return target

    # Single-track: target resolved relative to body root (en/) (2026-08-27 fix · previously vs SCRIPT_DIR, mis-writing into examples/activation/)
    if not os.path.isabs(target):
        target = os.path.normpath(os.path.join(body["body_root"], target))
    os.makedirs(os.path.dirname(target), exist_ok=True)
    with open(target, "w", encoding="utf-8") as f:
        f.write(build_profile(data, finalize.get("frozen_note", "")))
    print(f"\n✅ Onboarding complete! Owner profile frozen at: {target}")
    print(f"   🔒 Machine read-only: the machine only reads and executes, never modifies.")
    print(f"   ✏️ Only the owner may edit: just open and edit the file directly.")
    return target


def main():
    parser = argparse.ArgumentParser(description="GOAA First Onboarding")
    parser.add_argument("--config", default=CONFIG_PATH, help="path to the flow definition YAML")
    parser.add_argument("--dry-run", action="store_true", help="show the flow without interacting")
    args = parser.parse_args()

    config = load_config(args.config)
    run(config, dry_run=args.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
